server:
    port: 9000
    servletPath: /gpms

spring:
    datasource:
        url: jdbc:mysql://10.11.32.19:3306/uip
        username: ailife
        password: ailife
        continueOnError: false

